training_pipeline_config:
  pipeline_name: Give_Me_Some_Credit
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/Chirag1994/Datasets/main/dataset.rar
  raw_data_dir: raw_data
  zipped_download_dir: zipped_data
  ingested_dir: ingested_dir
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  transformed_dir: transform_data
  transformed_train: train
  transformed_test: test
  preprocessed_dir: preprocessed
  preprocessed_object_file_name: prerocessed.pkl

model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_auc: 0.5
  model_config_dir: config
  model_config_file_name: model.yaml

model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml

model_pusher_config:
  model_export_dir: saved_models
